name: Android Release Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Sign ABI APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set API keys for build
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> local.properties
          echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> local.properties

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build unsigned APKs (ABI split)
        run: ./gradlew clean assembleRelease

      - name: Sign release APKs
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload signed APKs
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apks
          path: app/build/outputs/apk/release/*.apk