name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Set Gradle as executable
        run: chmod +x ./gradlew

        
      - name: Set Api Key from Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo "TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug