name: Android Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set API keys for build
        run: |
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> local.properties
          echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> local.properties

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Clean & Build
        run: ./gradlew clean build