name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set TMDB API Key from Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo "TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties

      - name: Set Gradle as executable
        run: chmod +x ./gradlew

      - name: Clean, Build & Test
        run: ./gradlew clean assembleDebug test

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk