name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set Api Key from Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo "TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Cache Gradle Caches
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-cache
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-wrapper
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

      - name: Run Gradle tasks
        run: ./gradlew build --continue

      - name: Stop Gradle
        run: ./gradlew --stop